language: objective-c
osx_image: xcode12.4
env:
  global:
    - TMP_DIR=./tmp # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
    - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - (xcrun simctl list)
  - wget http://travisci.rubymotion.com/ -O RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion
  - eval "sudo motion activate $MY_RUBYMOTION_LICENSE"
  - sudo motion update
  - (motion --version)
  - (ruby --version)
  - motion repo
script: bundle exec rake spec